// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Copies content to clipboard, hides the window, and simulates Ctrl+V. */
	pasteItem: (contentType: string, textContent: string | null, imageData: string | null) => typedError<null, string>(__TAURI_INVOKE("paste_item", { contentType, textContent, imageData })),
	/**
	 *  Writes a file:// URI to the clipboard as text/uri-list, hides the window,
	 *  and simulates Ctrl+V. Wayland-only for now (shells out to wl-copy).
	 */
	pasteFileUri: (path: string) => typedError<null, string>(__TAURI_INVOKE("paste_file_uri", { path })),
	readClipboard: () => typedError<string, string>(__TAURI_INVOKE("read_clipboard")),
	readClipboardImage: () => typedError<[string, number, number] | null, string>(__TAURI_INVOKE("read_clipboard_image")),
	writeClipboard: (text: string) => typedError<null, string>(__TAURI_INVOKE("write_clipboard", { text })),
	writeClipboardImage: (base64Data: string) => typedError<null, string>(__TAURI_INVOKE("write_clipboard_image", { base64Data })),
	reinitializeClipboard: () => typedError<null, string>(__TAURI_INVOKE("reinitialize_clipboard")),
	parseEnvContent: (text: string) => __TAURI_INVOKE<([string, string])[]>("parse_env_content", { text }),
	setMonitoring: (enabled: boolean) => __TAURI_INVOKE<void>("set_monitoring", { enabled }),
	isWaylandSession: () => __TAURI_INVOKE<boolean>("is_wayland_session"),
	isCosmicDataControlEnabled: () => __TAURI_INVOKE<boolean>("is_cosmic_data_control_enabled"),
	/**
	 *  Downloads a media URL to a temporary file and returns the file path
	 *  along with a small PNG icon for the drag preview.
	 */
	downloadMediaToTemp: (url: string) => typedError<[string, string], string>(__TAURI_INVOKE("download_media_to_temp", { url })),
	getSetting: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_setting", { key })),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
	setToggleShortcut: (accelerator: string) => typedError<null, string>(__TAURI_INVOKE("set_toggle_shortcut", { accelerator })),
	getSessionToken: () => __TAURI_INVOKE<string | null>("get_session_token"),
	saveSessionToken: (token: string) => typedError<null, string>(__TAURI_INVOKE("save_session_token", { token })),
	deleteSessionToken: () => typedError<null, string>(__TAURI_INVOKE("delete_session_token")),
	isWebsocketConnected: () => __TAURI_INVOKE<boolean>("is_websocket_connected"),
	connectWebsocket: (urlString: string, bearerToken: string) => typedError<null, string>(__TAURI_INVOKE("connect_websocket", { urlString, bearerToken })),
	disconnectWebsocket: () => typedError<null, string>(__TAURI_INVOKE("disconnect_websocket")),
	sendWebsocketMessage: (message: string) => typedError<null, string>(__TAURI_INVOKE("send_websocket_message", { message })),
	insertClipboardItem: (params: InsertClipboardItemParams) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("insert_clipboard_item", { params })),
	getAllClipboardItems: (limit: number, offset: number, favoritesFirst: boolean) => typedError<ClipboardItemRow[], string>(__TAURI_INVOKE("get_all_clipboard_items", { limit, offset, favoritesFirst })),
	bumpClipboardItem: (id: number, sortOrder: string) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("bump_clipboard_item", { id, sortOrder })),
	dedupClipboardItem: (id: number) => typedError<number, string>(__TAURI_INVOKE("dedup_clipboard_item", { id })),
	clearClipboard: () => typedError<null, string>(__TAURI_INVOKE("clear_clipboard")),
	deleteClipboardItem: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_clipboard_item", { id })),
	updateClipboardSortOrder: (items: UpdateSortOrderParams[]) => typedError<null, string>(__TAURI_INVOKE("update_clipboard_sort_order", { items })),
	toggleClipboardItemFavorite: (id: number) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("toggle_clipboard_item_favorite", { id })),
};

/* Types */
export type ClipboardItemRow = {
	id: number,
	content_type: string,
	text_content: string | null,
	image_data: string | null,
	image_width: number | null,
	image_height: number | null,
	line_count: number | null,
	source_app: string | null,
	is_favorite: boolean,
	sort_order: string,
	kv_key: string | null,
	detected_date: string | null,
	detected_color: string | null,
	is_env: boolean,
	is_secret: boolean,
	note: string | null,
	content_hash: string | null,
	file_mime: string | null,
	created_at: string,
	updated_at: string,
};

export type InsertClipboardItemParams = {
	content_type: string,
	text_content: string | null,
	image_data: string | null,
	image_width: number | null,
	image_height: number | null,
	line_count: number | null,
	source_app: string | null,
	sort_order: string,
	kv_key: string | null,
	created_at: string,
	updated_at: string,
};

export type UpdateSortOrderParams = {
	id: number,
	sort_order: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

